### ISSUE TITLE
Saving simulation gives error

### ISSUE THREAD

**Issue by JohannesBuchner** [lucaskorol21/GO-RXR#44]
```
Traceback (most recent call last):
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/GUI_GO.py", line 9002, in _saveSimulation
    ds.saveSimulationHDF5(self.fname, sim_dict, self.version)
  File "/mnt/data/daten/PostDoc2/home/Downloads/GO-RXR/UTILS/data_structure.py", line 492, in saveSimulationHDF5
    simulated = f['Simulated_data']
                ~^^^^^^^^^^^^^^^^^^
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_debian_h5py_serial/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_debian_h5py_serial/_objects.pyx", line 54, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/_objects.pyx", line 55, in h5py._debian_h5py_serial._objects.with_phil.wrapper
  File "h5py/_debian_h5py_serial/h5o.pyx", line 189, in h5py._debian_h5py_serial.h5o.open
KeyError: "Unable to open object (object 'Simulated_data' doesn't exist)"
```

**Comment by jpcurbelo** [comment]
Hi! I wasn't able to reproduce exactly this issue, although, got `KeyError: "Unable to synchronously open object (object 'Simulated_data' doesn't exist)"` when saving the simulation. However, a `demo.h5` file is saved in the root dir as expected. We are working on fixing this and improving the saving process. In the meantime, could you, please, let us know if any file was saved when you tried? Thanks.

**Comment by jpcurbelo** [comment]
We have implemented some updates to the _load/save_ menus:

1- Got rid of the _Load/Save Orbitals_ entries. Commented the functions `_loadOrbitals` and `_saveOrbitals` and added this comment: "This should be implemented/updated on Jordan's update - summer 2024".
2- _Save_ _Simulation/Sample/Summary_ are disable when the GUI is loaded. _Save Simulation_ is also enabled after _Import Dataset_ or _Load ReMagX_.
- _Save Summary_ is  enabled at the end of `optimizationFinished`.
- _Save Summary_ is disabled after the user loads workspace (`_loadFile`) or load sample (`_loadSample`)
-  _Save Simulation_ and _Save Sample_ are enable when the user _Load Workspace_ (`_loadFile`) or _Save Workspace As_ (`_saveAsFile`). This procedure eliminates the issue the reviewer noticed - error when trying to save the simulation before saving the workspace.
- We added a (2s) pop-up message (and terminal log) to let the user know how the _saving_ went.
